repository:
  topics: image-compression, fastlane-plugin, ios, android, ruby, gem, swift, kotlin
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  allow_update_branch: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        checks: []
      enforce_admins: false
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      restrictions: null